### ISSUE TITLE
Intro - GitHub as a one-stop-shop

### ISSUE THREAD

**Issue by davidbridgwood** [moj-analytical-services/tech-radar-demo#1]
## Tasks:
- [ ] Who is the target audience
- [ ] Why store everything in GitHub
- [ ] Tech-Radar as an example
