### ISSUE TITLE
Actions, Pages and Discussions

### ISSUE THREAD

**Issue by davidbridgwood** [moj-analytical-services/tech-radar-demo#3]
# Tasks:
- [ ] create a github action to publish to gihub pages
- [ ] add a discussion and update labels
- [ ] create a discussion template
