### ISSUE TITLE
Docs, Diagrams and Slides

### ISSUE THREAD

**Issue by davidbridgwood** [moj-analytical-services/tech-radar-demo#4]
## Tasks
- [ ] Wikis vs Docs
- [ ] create `docs/` directory
- [ ] add mermaid diagram to the README
- [ ] demo excalidraw and add to the README
- [ ] create a simple marp-slide with winners and losers
