### ISSUE TITLE
Assess AWS Quicksight

### ISSUE THREAD

**Issue by davidbridgwood** [moj-analytical-services/tech-radar-demo#9]
# description
Look into AWS Quicksight as a possible BI tool

## TODO:
- [ ] #10
- [ ] work with users to understand their BI needs
- [ ] attempt to connect to data on the platform
- [ ] assess features against user needs
- [ ] write up assessment of work and present back
